categories:
  - title: 'Features'
    label: 'feature'
    label: 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
template: |
  ## What’s Changed

  $CHANGES