blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/NREL/reV/discussions
    about: |
      Ask questions about the reV suite (including reVX) and discuss with the developers and other users
      here. If you have a question like "How do I run wind turbine setbacks for Colorado?", please
      include a self-contained reproducible example of what you have tried already, if possible.
