package:
    name: nrel-revx
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - dask
    - geopandas
    - nrel-rev>=0.4.37
    - psycopg2
    - pyproj
    - pywavelets
    - rasterio
    - rtree
    - scikit-learn
    - shapely
    - toolz
    - xarray
  run:
    - python
    - pip
    - dask
    - geopandas
    - nrel-rev>=0.4.37
    - psycopg2
    - pyproj
    - pywavelets
    - rasterio
    - rtree
    - scikit-learn
    - shapely
    - toolz
    - xarray
  run-constrained:
    - earthpy

about:
  home: "https://github.com/NREL/reVX"
  license: BSD 3-Clause
  summary: "Renewable Energy Potential(V) eXchange Tool: reVX"
  doc_url: "https://nrel.github.io/reVX"
  dev_url: "https://github.com/NREL/reVX"
