package:
    name: nrel-revx
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - click
    - dask
    - geopandas
    - h5py>=2.10.0,!=3.0.0
    - nrel-rex>=0.2.29
    - nrel-rev>=0.4.31
    - numpy>=1.16
    - pandas
    - psutil
    - psycopg2
    - pyproj
    - pywavelets
    - rasterio
    - scikit-learn
    - scipy
    - shapely
    - toolz
    - xarray
  run:
    - python
    - pip
    - click
    - dask
    - geopandas
    - h5py>=2.10.0,!=3.0.0
    - nrel-rex>=0.2.29
    - nrel-rev>=0.4.31
    - {{ pin_compatible('numpy') }}
    - pandas
    - psutil
    - psycopg2
    - pyproj
    - pywavelets
    - rasterio
    - scikit-learn
    - scipy
    - shapely
    - toolz
    - xarray

about:
  home: "https://github.com/NREL/reVX"
  license: BSD 3-Clause
  summary: "Renewable Energy Potential(V) eXchange Tool: reVX"
  doc_url: "https://nrel.github.io/reVX"
  dev_url: "https://github.com/NREL/reVX"
