name: Pytests

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.11]
        include:
          - os: ubuntu-latest
            python-version: '3.10'
          - os: ubuntu-latest
            python-version: 3.9

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        miniconda-version: "latest"
    - name: Install conda dependencies
      shell: bash -l {0}
      working-directory: ${{ github.workspace }}
      run: |
        conda install rtree pip pytest
        pip install --upgrade setuptools
        pip install -e .
        pip install HOPP==0.0.5
    - name: Run pytest and Generate coverage report
      shell: bash -l {0}
      run: |
        pytest -v
