name: PR Merge

on:
  pull_request:
    types: [opened, edited, synchronize, closed]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pip install pytest
        python -m pytest
