name: Release Drafter

on:
  pull_request:
    types: closed

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}